# Generated by Django 2.0 on 2020-06-26 12:37

import DBMS.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('mapB64', models.CharField(max_length=1048576)),
                ('poster', models.CharField(max_length=1048576)),
                ('freezed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteText', models.CharField(max_length=1048576)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=20)),
                ('userPassword', models.CharField(max_length=40)),
                ('avatar', models.CharField(max_length=1048576)),
                ('name', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('lab', models.CharField(max_length=100)),
                ('group', djongo.models.fields.ArrayField(model_container=DBMS.models.Project)),
                ('collection', djongo.models.fields.ArrayField(model_container=DBMS.models.Project)),
                ('notification', djongo.models.fields.EmbeddedField(model_container=DBMS.models.Notification, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('nthGroup', models.IntegerField()),
                ('topic', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('tag', djongo.models.fields.ArrayField(model_container=models.CharField(verbose_name=100))),
                ('grade', models.IntegerField()),
                ('browse', models.IntegerField()),
                ('comment', djongo.models.fields.ArrayField(model_container=DBMS.models.Comment)),
                ('board', djongo.models.fields.EmbeddedField(model_container=DBMS.models.Board, null=True)),
                ('calender', djongo.models.fields.EmbeddedField(model_container=DBMS.models.Calender, null=True)),
                ('teacher', models.CharField(max_length=20)),
                ('leader', models.CharField(max_length=20)),
                ('members', djongo.models.fields.ArrayField(model_container=models.CharField(max_length=20))),
            ],
        ),
    ]
