# Generated by Django 2.0 on 2020-06-26 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBMS', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
